version: '3.5'

services:
  app:
    build: .
    image: loradecoder
    # container-name implies only one instance
    container_name: loradecoder
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # ONLY for development mode
      # ==> REQUIRES YOU TO BE WITHIN the loradecoder DIRECTORY !!
      - ${PWD}/app:/opt/app
    network_mode: bridge
    ports:
      - "8011:5000"     # Web app
      - "2231:22"       # SSH
    #env_file:
      # environment section has precedence over env_file
      #- ${PWD}/dataCOllector.env
    environment:
      # DEBUG is the app. debugging feature
      # SIM is the read-only mode (i.e no write to any database) for testing purposes
      # FLASK_ENV=development activate ALL flask debug features
      # FLASK_DEBUG as you guessed ;)
      - PYTHONUNBUFFERED=1
      - FLASK_DEBUG
      - FLASK_ENV
      - DEBUG
      - SIM
      # MQTT
      - MQTT_SERVER
      - MQTT_PORT
      #- MQTT_USER=loradecoder
      # [nov.20] only for tests
      - MQTT_USER=test
      - MQTT_PASSWD
      # json format for MQTT_TOPICS to subscribe to
      - MQTT_TOPICS=[ "_lora/#", "TestTopic/lora/#" ]
      - MQTT_UNITID

